#pragma once

#include "NativeGameplayTags.h"

namespace L1GameplayTags
{
	// InitState
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataAvailable);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_DataInitialized);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	// Input
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Primary);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Secondary);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Tertiary);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Quaternary);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Quinary);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeEquip_Senary);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Confirm);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Ability_Cancel);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_MainHand);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_OffHand);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Skill_1);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack_Skill_2);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_Inventory);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_WorldMap);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Widget_ClassSelection);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SetDestination);
	
	// Ability
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsBlocked);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_TagsMissing);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Networking);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crouch);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Knockback);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stun);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Check);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Dash_Active);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Check);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Active);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ChangeEquip);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_1);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_2);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_3);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Bow);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill_1);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_Skill_2);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Throw);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Drink);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS_Bow);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ADS_Throw);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Active);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Object);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_Inventory);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_WorldMap);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Widget_ClassSelection);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_HitReact);

	// Status
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouch);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Jump);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Knockback);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stun);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dead);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Skill);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Throw);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Drink);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Block);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ChangeEquip);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Bow);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Ready);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_ADS_Throw);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Dash);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprint);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Succeeded);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Failed);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Interact);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_HitReact);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_RejectHitReact);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_StaminaRecoveryBlock);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_PiercingShot);

	// Gameplay Event
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Tick);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Spell);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Play);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_CameraShake);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ChangeEquip);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ArrowVisibility);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Potion_Drink);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Potion_Fill);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Knockback);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Stun);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Bow_ADS);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_HitReact);
	
	// Gameplay Event_Network
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Skill_1);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Skill_2);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset_Skill_1);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Reset_Skill_2);
	
	// Cheat
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	// Movement
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_NavWalking);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Swimming);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Custom);

	// Message
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Notification);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Notice);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Progress);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyInventory);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherInventory);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_MyEquipment);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Initialize_OtherEquipment);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Input);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Progress_Construct);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_HUD_Spell_Progress_Refresh);

	// SetByCaller
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_InitialAttribute_Health);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_InitialAttribute_Mana);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseDamage);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseHealth);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseMana);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseStamina);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingDamage);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingHealth);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingMana);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingStamina);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeed);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeedPercent);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Strength);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Defense);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Agility);
	L1GAME_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Intelligence);

	// GameplayCue
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Attack);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Impact);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Cast_Fireball);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Cast_Skill);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill_Targeting_Burst);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill_Targeting_Loop);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Overlay);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Loop);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Success);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Fail);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Skill_Buff);

	// Cooldown
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Bow_Fire);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Jump);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Dash);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Statue);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Sprint);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_1);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Skill_2);

	// GamePhase
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_PreGame);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_Game);
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(GamePhase_PostGame);

	// HUD
	L1GAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HUD_Slot_Reticle);

	L1GAME_API	extern const TMap<uint8, FGameplayTag> MovementModeTagMap;
	L1GAME_API	extern const TMap<uint8, FGameplayTag> CustomMovementModeTagMap;

	L1GAME_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
};
